### ISSUE TITLE
扣點、扣券、儲值紀錄table 沒有視覺滑動指引

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#1]
目前這個4個畫面在我的裝置上都有超出尺寸的問題，
在原來的網頁版本應該是RWD畫面會隨裝置尺寸變動。
問題的狀況如附圖。
![image](https://user-images.githubusercontent.com/25201055/183937856-eb24785b-fb0a-4d9c-ad2c-e6df6507db6b.png)
![image](https://user-images.githubusercontent.com/25201055/183937891-9b9185aa-4e25-465c-ab28-1f6af26333cc.png)
![image](https://user-images.githubusercontent.com/25201055/183937913-b80fe0ed-a009-45fe-a5e9-7f413da67cfa.png)
![image](https://user-images.githubusercontent.com/25201055/183937940-125816e4-7aef-4eda-9bd7-f9ce47a3e1b0.png)

**Comment by maple135790** [comment]
這個table 是可以左右滑動的
在視覺上還沒有提供可滑動的指引

**Comment by maple135790** [comment]
已於 5ee67d400751ffafaed7ce1c5b761ed29554a877 修正
表格取消左右滑動
