### ISSUE TITLE
首頁畫面及元件問題

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#2]
目前首頁上有2個問題

1. 此處的親密度會從浮點數轉成整數
2. 此處應該會被帶到這2個Youtube頻道

https://www.youtube.com/channel/UCEbHRn4kPMzODDgsMwGhYVQ
https://www.youtube.com/c/X50MusicGameStation-onAir

![photo_2022-08-10_23-02-59](https://user-images.githubusercontent.com/25201055/183939622-07bee9bf-eb1a-4d7c-811a-09a8cef1b861.jpg)

**Comment by maple135790** [comment]
已修正
