### ISSUE TITLE
使用ScanPay無反應

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#26]
使用QR Code掃描時無法正常在機台進行扣款, 但目前還不確定是否為該機台(Chunithm)周遭環境太暗所引起.
後續有針對平板掃描確認是有反應, 先提出待後續追蹤

**Comment by maple135790** [comment]
scan pay 的功能還沒有實現在app 上。
估計scan pay 需要花上1~2 wk 的工作時間。
因為android 跟ios 的nfc 讀取流程似乎不太一樣，而nfc tag 的資料還需要跟0mu 確認

如果需要，可以再開一個 寫未實現功能 的單，要寫在readme 之類的地方 那樣
