### ISSUE TITLE
使用切換衣服功能並無即時重渲染

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#27]
切換衣服時 跳出成功訊息並未將人物圖像進行更換 須待回首頁重渲染後 才回復正常 此為網頁版共通問題

https://github.com/maple135790/x50pay/assets/25201055/668a8c28-c794-414b-9462-31e6e6162b83

**Comment by maple135790** [comment]
這個我可以讓他選擇完後，返回主頁時重新fetch
然後modal 有點太大，我再把他調成單獨頁面
