### ISSUE TITLE
重寫README

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#28]
幫助想要開發此專案的人提供相對應的指引(專案簡介, 如何build, 相關連絡資訊 etc.)
預期先提供中文版 後續若有需要再增設其他語言

**Comment by maple135790** [comment]
readme 還真的不知道怎麼寫比較好
如果說是技術層面的how-to-build 到還好，但如果是介紹app 的話
好像是需要跟staff 們討論，才能寫的東西 (?)

**Comment by junk87** [comment]
App介紹比較偏User Guide
我看x50粉專上有放功能圖解那樣
或許可以用一個gitbook或hackMD之類的工具做彙整
方便非開發的使用者參考 不過這可能還是要徵求他們的意見

**Comment by maple135790** [comment]
已持續更新，關閉此 issue
