### ISSUE TITLE
掃描QRCode付款黑畫面及信用卡/線上加值按鈕無反應

### ISSUE THREAD

**Issue by junk87** [maple135790/x50pay#3]
目前使用首頁的掃描QRCode選項會出現黑畫面，已確認應用程式有相機權限，
目前可以靠先手機鎖定後再解除鎖定，相機畫面就會顯示出來
此外點信用卡/線上加值按鈕無反應
![image](https://user-images.githubusercontent.com/25201055/183941397-8261d62b-0c59-4c0a-b783-b03da1ea289a.png)
![image](https://user-images.githubusercontent.com/25201055/183941436-41f1b13b-32f0-4647-899c-811fe3ee9ec8.png)

**Comment by maple135790** [comment]
已於 e943c69 新增
